const defaultTheme = {
  "--color-primary": "#107eac",
  "--accent-main": "var(--color-primary)",
  "--color-primary-inverse": "white",
  "--color-secondary": "#529bb6",
  "--color-secondary-inverse": "white",
  "--color-tertiary": "#63d6de",
  "--color-tertiary-inverse": "white",
  "--color-warning": "#940019",
  "--color-header": "var(--color-primary)",
  "--color-subheader": "var(--color-secondary)",
  "--color-text-basic": "black",
  "--card-color": "#ffffff",
  "--field-color": "white",
  "--bg-opacity": "0.4",
  "--bg-color": "#00598736",
  "--color-shadow": "#90909080",
  "--color-inactive": "#808080",
  "--color-inactive-alt": "white",
  "--color-disabled": "#808080",
  "--color-disabled-alt": "white",
  "--outer-card-color": "#FFFFFFb0",
  "--color-outline": "#90909080",
  "--map-marker-color": "#576d53",
  "--color-separator": "#555555",
  "--welcome-bg-color": "var(--card-color)",
};

export default defaultTheme;
