const defaultTheme = {
  "--color-primary": "#108fac",
  "--accent-main": "var(--color-primary)",
  "--color-primary-inverse": "white",
  "--color-secondary": "#52b69a",
  "--color-secondary-inverse": "white",
  "--color-tertiary": "#63deb2",
  "--color-tertiary-inverse": "white",
  "--color-warning": "#940019",
  "--color-header": "var(--color-primary)",
  "--color-subheader": "var(--color-secondary)",
  "--color-text-basic": "black",
  "--card-color": "#ffffff",
  "--field-color": "white",
  "--bg-opacity": "1",
  "--bg-color": "#87ccef80",
  "--color-shadow": "#90909080",
  "--color-inactive": "#808080",
  "--color-inactive-alt": "white",
  "--color-disabled": "#808080",
  "--color-disabled-alt": "white",
  "--outer-card-color": "#FFFFFFb0",
  "--color-outline": "#90909080",
  "--map-marker-color": "#576d53",
};

export default defaultTheme;
