const eucalyptusThemeDark = {
  "--color-primary": "#495c46",
  "--accent-main": "var(--color-primary)",
  "--color-primary-inverse": "white",
  "--color-secondary": "#7aa76f",
  "--color-secondary-inverse": "white",
  "--color-tertiary": "#84a95a",
  "--color-tertiary-inverse": "white",
  "--color-warning": "#940019",
  "--color-header": "var(--color-secondary)",
  "--color-subheader": "var(--color-tertiary)",
  "--color-text-basic": "white",
  "--card-color": "#292929",
  "--field-color": "#363636",
  "--bg-opacity": "0.07",
  "--bg-color": "#101510",
  "--color-shadow": "#00000080",
  "--color-inactive": "#27331b",
  "--color-inactive-alt": "white",
  "--color-disabled": "#3c3c3c",
  "--color-disabled-alt": "white",
  "--outer-card-color": "#00000080",
  "--color-outline": "#90909080",
  "--map-marker-color": "#495c46",
};

export default eucalyptusThemeDark;
