const oceanThemeDark = {
  "--color-primary": "#142350",
  "--accent-main": "var(--color-primary)",
  "--color-primary-inverse": "white",
  "--color-secondary": "#4f85a6",
  "--color-secondary-inverse": "#161616",
  "--color-tertiary": "#4b989b",
  "--color-tertiary-inverse": "white",
  "--color-warning": "#940019",
  "--color-header": "var(--color-secondary)",
  "--color-subheader": "var(--color-tertiary)",
  "--color-text-basic": "white",
  "--card-color": "#292929",
  "--field-color": "#363636",
  "--bg-opacity": "0.05",
  "--bg-color": "#080d14",
  "--color-shadow": "#00000080",
  "--color-inactive": "#405477",
  "--color-inactive-alt": "white",
  "--color-disabled": "#3c3c3c",
  "--color-disabled-alt": "white",
  "--outer-card-color": "#00000080",
  "--color-outline": "#90909080",
  "--map-marker-color": "#4f85a6",
};

export default oceanThemeDark;
