const oceanTheme = {
  "--color-primary": "#1458d6",
  "--accent-main": "var(--color-primary)",
  "--color-primary-inverse": "white",
  "--color-secondary": "#0d6b96",
  "--color-secondary-inverse": "white",
  "--color-tertiary": "#00b8a1",
  "--color-tertiary-inverse": "white",
  "--color-warning": "#940019",
  "--color-header": "var(--color-primary)",
  "--color-subheader": "var(--color-secondary)",
  "--color-text-basic": "black",
  "--card-color": "#ffffff",
  "--field-color": "white",
  "--bg-opacity": "0.7",
  "--bg-color": "#d7e1ff",
  "--color-shadow": "#90909080",
  "--color-inactive": "#808080",
  "--color-inactive-alt": "white",
  "--color-disabled": "#808080",
  "--color-disabled-alt": "white",
  "--outer-card-color": "#FFFFFFb0",
  "--color-outline": "#90909080",
  "--map-marker-color": "#1458d6",
};

export default oceanTheme;
