const purpleTheme = {
  "--color-primary": "#3c006b",
  "--accent-main": "var(--color-primary)",
  "--color-primary-inverse": "white",
  "--color-secondary": "#6800b8",
  "--color-secondary-inverse": "white",
  "--color-tertiary": "#6800b8",
  "--color-tertiary-inverse": "white",
  "--color-warning": "#940019",
  "--color-header": "var(--color-primary)",
  "--color-subheader": "var(--color-secondary)",
  "--color-text-basic": "black",
  "--card-color": "#ffffff",
  "--field-color": "white",
  "--bg-opacity": "0.7",
  "--bg-color": "#f0e7fa",
  "--color-shadow": "#90909080",
  "--color-inactive": "#808080",
  "--color-inactive-alt": "white",
  "--color-disabled": "#808080",
  "--color-disabled-alt": "white",
  "--outer-card-color": "#FFFFFFb0",
  "--color-outline": "#90909080",
  "--map-marker-color": "#3c006b",
};

export default purpleTheme;
